name: Terraform Promote

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to apply"
        required: true
        type: choice
        options:
          - stage
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    name: Apply ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: envs/${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform plan
        run: terraform plan -no-color
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}