name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    name: Terraform apply via HCP Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}