name: Terraform PR Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-pr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev]

    defaults:
      run:
        working-directory: envs/${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive ../..

      - name: Terraform init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint init
        run: tflint --init --config ../../.tflint.hcl

      - name: TFLint run
        run: tflint --recursive --config .tflint.hcl

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          soft_fail: true

      - name: Terraform plan
        run: terraform plan -no-color
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}